---
apiVersion: v1
kind: Service
metadata:
  name: "tp-api-demo-producer"
  labels:
    purpose: tp-api-demo
spec:
  type: ClusterIP
  selector:
    service: tp-api-demo-producer
  ports:
    - name: proxied
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tp-api-demo-producer"
  labels:
    service: tp-api-demo-producer
    purpose: tp-api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tp-api-demo-producer
  template:
    metadata:
      labels:
        service: tp-api-demo-producer
        purpose: tp-api-demo
    spec:
      containers:
        - name: apitest
          image: docker.io/thhal/tp-api-demo-producer:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: APP_PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "DEBUG"
          resources:
            limits:
              memory: 512Mi
